### ISSUE TITLE
can it supports stack operation such as "push {r0,r7}"

### ISSUE THREAD

**Issue by Pr0214** [linouxis9/ProjectARM#2]
Dear developer team, I sincerely love using your software for assembly teaching. Does this software support stack operation?
![image](https://user-images.githubusercontent.com/44285766/71607813-8ba3d180-2bb7-11ea-97ee-f9d27b1bde74.png)

**Comment by linouxis9** [comment]
Hi @Pr0214 ! We are very glad to know that you are enjoying using our software.
Concerning stack operations, yes, we do support them, however, you do have to initialize the SP register with an address pointing to somewhere accessible in the RAM to be able to use this feature. Please keep me updated if it worked by changing the SP register before using stack operations !
Thank you so much !
Furthermore, I'm going to make a commit to initialize the SP with a default value to prevent this shortcoming.

**Comment by linouxis9** [comment]
As a heads up, you may want to try latest ARMStrong's release, stack operations should now work as expected ! @Pr0214 
If there are any more problems, please feel free to create another issue.
Thank you for using our software !
